# Site settings
title: "Nathaniel Hayden - Software Developer"
description: "Nathaniel Hayden - Software Developer"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Nathaniel Hayden"
resume_title:                   "Software Developer, dedicated do-gooder"
#resume_contact_email:           "nope@nope.com"
#resume_contact_telephone:       "555-555-5555"
resume_contact_address:         "Greater Seattle Area"
#resume_header_contact_info: "Greater Seattle Area | 555-555-5555 | nope@nope.com"
resume_header_intro: "<p>I dig deep to create a great experience for users, and I love working for a cause. As part of the Bioconductor core team I delivered scalable, efficient cross-platform scientific programming solutions; built a reputation for raising the bar technically; and used my drive and creativity to dive in headfirst and deliver quickly in new domains.</p> <ul><li>Primary technologies&#58; Java (proficient), C++ (proficient), R (proficient), JavaScript/CSS/HTML (proficient), Python (proficient), SQL (proficient)</li>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
#resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
#resume_section_links:           true
#resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/nhayden"
  #resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/nathanielhayden"
  # resume_instagram_url:         "insert your Instagram URL here"
  #resume_website_url:           "http://joelglovier.com"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
